### ISSUE TITLE
Releases not updated

### ISSUE THREAD

**Issue by alexolog** [EionRobb/pidgin-opensteamworks#189]
The latest Windows release is from over 4 years ago.

**Comment by nodiscc** [comment]
The Linux .so has not been released for 4 years also. It's straightforward to build but please provide a prebuilt .so as the README indicates to grab the binary from the releases page.

@EionRobb , ping.

**Comment by EionRobb** [comment]
Man, 4 years?  That's nuts

https://github.com/EionRobb/pidgin-opensteamworks/releases/tag/1.7

:)

**Comment by nodiscc** [comment]
> Man, 4 years? That's nuts

:eyes: now that you say it... yeah wtf. I think I have been running your plugin daily since the 1.6 release, so thank you for maintaining this!

And thanks for releasing 1.7, I think this can be closed.

[Ansible tasks](https://gitlab.com/nodiscc/dlc-utils/blob/master/tasks/pidgin-opensteamworks.yml) to install the plugin from binary, for what it's worth. I still plan on working on a Debian package (https://github.com/EionRobb/pidgin-opensteamworks/issues/121)... someday...

Cheers
