### ISSUE TITLE
No key= token.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/pidgin-opensteamworks#81]
```
Pidgin fails to login with 'Unknown error', stemming from this:

% curl "api.steampowered.com/ISteamWebUserPresenceOAuth/Logon/v0001" -F 
"access_token=(redacted)"
<html><head><title>Unauthorized</title></head><body><h1>Unauthorized</h1>Access 
is denied. Retrying will not help. Please verify your <pre>key=</pre> 
parameter.</body></html>
```

Original issue reported on code.google.com by `166...@gmail.com` on 3 Aug 2014 at 10:57

**Comment by Det7** [comment]
@GoogleCodeExporter hi. how can I contact you? 

I also encountered the same problem.

Goal
- Setup a CURL command to automatically get data from a WebAPI which requires a key to be passed (I have the key).

What I did so far?
1. Registered for GCP free trial
2. Setup a minimal VM instance called test-instance
3. Clicked Remote Access - SSH
4. Used SSH/putty - to ping the website w/c was successful
5. Used SSH/putty - Typed "curl <webapi address">
6. Encountered below error:
"Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter"

I'm still checking if there is an error with my token number, but outside of this, can it be due to some CA/certificates, etc?

If I use the WebAPI directly in my laptop browser - it gives me the data I need.

Thanks in advance!

Update: I also tried running "curl <webapi address>" through command line in my laptop and it gave the same error.

This might be more of a curl problem than GCP?

**Comment by EionRobb** [comment]
@Det7 what is GCP and what does it have to do with Steam and why are you posting on a two year old closed issue about it?

**Comment by Det7** [comment]
@EionRobb Google Cloud Platform. Apologies for replying to this, but was really looking into being able to automate CURL calling Steam API for Dota 2.
